name = "VoxelModel"
uuid = "4956fa17-11d8-4a0b-a900-0a865cb13992"
version = "2.3.0"
authors = ["Jake W. Liu"]

[deps]
BatchAssign = "e837618a-1c15-48db-beb0-68297dffdb28"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyGeometries = "da4dd95e-df4f-4caf-ac06-cee3b0f5c2e6"
PlotlySupply = "a389b534-8bca-4fe3-8ff2-14829cd8824f"

[compat]
BatchAssign = "1"
Combinatorics = "1"
JLD = "0.13.5"
PlotlyGeometries = "2.3.0"
PlotlySupply = "1.4.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
